### pyTorch import

In [1]:
import torch # pyTorch import
torch.__version__ # pyTorch version

'2.2.2+cu121'

### Scalar

In [2]:
# scalar

scalar = torch.tensor(7) # making scalar tensor (pyTorch.tensor class)
scalar

tensor(7)

In [3]:
scalar.ndim # scalar tensor dimensions

0

In [4]:
scalar.item() # method used on one-dimensional tensor returns python scalar object

7

### Vector

In [5]:
vector = torch.tensor([1, 2]) # making vector tensor (pyTorch.tensor class)
vector

tensor([1, 2])

In [6]:
vector.ndim # vector tensor dimensions

1

In [7]:
vector.shape # .shape returns num of elements in tensor

torch.Size([2])

### Matrix

In [8]:
matrix = torch.tensor(
  [
    [1, 2],
    [3, 4]
  ]
)
matrix

tensor([[1, 2],
        [3, 4]])

In [9]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 2])

### Tensor

In [11]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

In [14]:
random_tensor = torch.rand(size=(2, 5))
random_tensor

tensor([[0.4865, 0.7070, 0.3112, 0.5287, 0.3362],
        [0.0923, 0.5738, 0.2563, 0.9997, 0.2561]])

In [15]:
random_tensor_imagine = torch.rand(size=(224, 224, 3))
random_tensor_imagine

tensor([[[0.3420, 0.9124, 0.9191],
         [0.4935, 0.2134, 0.9132],
         [0.2579, 0.1758, 0.8176],
         ...,
         [0.0968, 0.3906, 0.9940],
         [0.8364, 0.1332, 0.6020],
         [0.8530, 0.4358, 0.2371]],

        [[0.3202, 0.9735, 0.4243],
         [0.1668, 0.3501, 0.8828],
         [0.5308, 0.8688, 0.2645],
         ...,
         [0.5560, 0.7699, 0.0603],
         [0.1598, 0.9222, 0.8265],
         [0.4497, 0.1863, 0.2842]],

        [[0.6696, 0.2088, 0.8264],
         [0.8200, 0.9517, 0.4163],
         [0.7369, 0.8574, 0.0174],
         ...,
         [0.3172, 0.3753, 0.7939],
         [0.3033, 0.1643, 0.0309],
         [0.8115, 0.7132, 0.3413]],

        ...,

        [[0.5010, 0.4289, 0.6696],
         [0.8023, 0.1455, 0.9359],
         [0.9470, 0.1264, 0.3636],
         ...,
         [0.3852, 0.9467, 0.8116],
         [0.5658, 0.0468, 0.4608],
         [0.8114, 0.9103, 0.1264]],

        [[0.8555, 0.8187, 0.7798],
         [0.2617, 0.2756, 0.4160],
         [0.

In [16]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

### Range tensors

In [17]:
zero_to_ten_deprecated = torch.range(0, 10)
zero_to_ten_deprecated

C:\Users\ciell\AppData\Local\Temp\ipykernel_3720\201814837.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [18]:
zero_to_ten = torch.arange(0, 10, 1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [20]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor, float_32_tensor.dtype, float_32_tensor.device

(tensor([3., 6., 9.]), torch.float32, device(type='cpu'))

In [21]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [22]:
some_tensor = torch.rand(3, 4)

print(some_tensor)
print(f'shape of tensor: {some_tensor.shape}')
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Device tensor is stored on: {some_tensor.device}')

tensor([[0.4794, 0.7797, 0.6552, 0.6504],
        [0.8152, 0.3473, 0.0488, 0.3486],
        [0.3473, 0.4341, 0.0318, 0.5183]])
shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Manipulating tensors

#### Basic operations

In [23]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [24]:
tensor * 10

tensor([10, 20, 30])

In [25]:
tensor -= 10
tensor

tensor([-9, -8, -7])

In [26]:
tensor += 10
tensor

tensor([1, 2, 3])

In [27]:
print(tensor, '*', tensor)
print('is equal:', tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
is equal: tensor([1, 4, 9])


#### matrix multiplication

In [28]:
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [29]:
tensor * tensor

tensor([1, 4, 9])

In [30]:
torch.matmul(tensor, tensor)

tensor(14)

In [31]:
tensor @ tensor

tensor(14)

In [32]:
tensor = torch.rand(100000)

In [33]:
%%time

value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: total: 625 ms
Wall time: 647 ms


tensor(33340.3828)

In [34]:
tensor = torch.rand(100000)

In [35]:
%%time

torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 3.63 ms


tensor(33241.2891)

#### Shape errors

matmul with error:

In [36]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

matmul without error:

In [ ]:
torch.matmul(tensor_B.T, tensor_A)

tensor([[ 76., 100.],
        [103., 136.]])

In [ ]:
torch.matmul(tensor_B, tensor_A.T)

tensor([[ 27.,  61.,  95.],
        [ 30.,  68., 106.],
        [ 33.,  75., 117.]])

`torch.mm` is a shortprint of `torch.matmul`

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

### Linear

In [41]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2,
                         out_features=6)
x = tensor_A
output = linear(x)
print(f'Input shape: {x.shape}')
print(f'Output:\n{output}\n\nOutput shape: {output.shape}')

Input shape: torch.Size([3, 2])
Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


### Agregation

In [42]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

Agregation that returns python objects

In [45]:
print(f'max: {x.max()}')
print(f'min: {x.min()}')
print(f'mean: {x.type(torch.float32).mean()}')
print(f'sum: {x.sum()}')

max: 90
min: 0
mean: 45.0
sum: 450


Agregation that returns tensor objects

In [51]:
print(torch.max(x))
print(torch.min(x))
print(torch.mean(x.type(torch.float32)))
print(torch.sum(x))

tensor(90)
tensor(0)
tensor(45.)
tensor(450)


argmin & argmax

In [53]:
tensor = torch.arange(10, 100, 10)
print(f'Tensor: {tensor}')

print(f'value where max value occurs: {tensor.argmax()}')
print(f'value where min value occurs: {tensor.argmin()}')

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
value where max value occurs: 8
value where min value occurs: 0


### Changing tensor datatypes

In [54]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [55]:
tensor_float_16 = tensor.type(torch.float16)
tensor_float_16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [56]:
tensot_int_8 = tensor.type(torch.int8)
tensot_int_8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

### Reshaping

In [67]:
tensor = torch.arange(1., 8.)
tensor, tensor.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [68]:
tensor_reshaped = tensor.reshape(1, 7)
tensor_reshaped, tensor_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [69]:
z = tensor.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [70]:
z[:, 0] = 0
z, tensor

(tensor([[0., 2., 3., 4., 5., 6., 7.]]), tensor([0., 2., 3., 4., 5., 6., 7.]))

In [74]:
print(f"Previous tensor_reshaped: {tensor_reshaped}")
print(f"Previous shape: {tensor_reshaped.shape}")

# Remove extra dimension from tensor_reshaped
x_squeezed = tensor_reshaped.squeeze()
print(f"\nNew tensor_reshaped: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor_reshaped: tensor([[0., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor_reshaped: tensor([0., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [75]:
x_original = torch.rand(size=(224, 224, 3))
x_permuted = x_original.permute(2, 0, 1)
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [78]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [79]:
x[:, 0]

tensor([[1, 2, 3]])

In [82]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [83]:
x[:, 0, 0]

tensor([1])

In [84]:
x[0, 0, :]

tensor([1, 2, 3])

### pyTorch & numPy friendship

In [85]:
import numpy as np

In [90]:
arr = np.arange(1.0, 8.0)
tensor = torch.from_numpy(arr)
arr, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [91]:
arr += 1
arr, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [93]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [95]:
tensor += 1
tensor, numpy_tensor

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([3., 3., 3., 3., 3., 3., 3.], dtype=float32))

### Reproductibility

In [103]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.3165, 0.6236, 0.2279, 0.4962],
        [0.7377, 0.0042, 0.9454, 0.1770],
        [0.6159, 0.2141, 0.4242, 0.9886]])

Tensor B:
tensor([[0.8235, 0.5554, 0.7254, 0.0261],
        [0.6818, 0.8763, 0.6799, 0.6484],
        [0.9866, 0.9625, 0.9333, 0.4565]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [104]:
import random

In [105]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

### CUDA using

In [106]:
!nvidia-smi

Tue Apr 30 22:07:26 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 546.12                 Driver Version: 546.12       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4060 ...  WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   45C    P0              16W / 115W |      0MiB /  8188MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [107]:
torch.cuda.is_available()

True

In [108]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [109]:
torch.cuda.device_count()

1

In [113]:
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [114]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [115]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)

In [116]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')