# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
import torch


tensor = torch.rand(7, 7)
tensor

tensor([[0.7662, 0.6398, 0.1360, 0.9898, 0.8560, 0.8888, 0.7016],
        [0.3788, 0.9363, 0.5795, 0.0535, 0.0454, 0.2629, 0.0211],
        [0.4724, 0.9679, 0.8898, 0.4644, 0.5813, 0.1566, 0.2800],
        [0.0977, 0.5562, 0.6884, 0.8965, 0.9116, 0.5998, 0.2991],
        [0.8058, 0.5451, 0.5226, 0.3559, 0.5062, 0.5273, 0.5335],
        [0.6958, 0.0468, 0.6976, 0.9325, 0.1397, 0.2149, 0.0041],
        [0.2043, 0.5032, 0.7964, 0.8775, 0.5443, 0.0606, 0.4264]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
tensor2 = torch.rand(1, 7)

tensor @ tensor2.T

tensor([[1.0393],
        [0.6788],
        [0.9920],
        [1.0466],
        [0.8494],
        [0.5729],
        [0.8157]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
torch.manual_seed(0)


tensor = torch.rand(7, 7)
tensor2 = torch.rand(1, 7)

tensor @ tensor2.T

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [37]:
torch.manual_seed(1234)

tensor_gpu = torch.rand(2, 3, device='cuda')
tensor_gpu2 = torch.rand(2, 3, device='cuda')

(tensor_gpu, tensor_gpu2)

(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.6208, 0.0276, 0.3255],
         [0.1114, 0.6812, 0.3608]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [39]:
tensor_gpu @ tensor_gpu2.T

tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [43]:
torch.max(tensor_gpu)

tensor(0.9737, device='cuda:0')

In [44]:
torch.min(tensor_gpu)

tensor(0.1272, device='cuda:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [9]:
# Find arg max


# Find arg min



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [10]:
# Set seed


# Create random tensor


# Remove single dimensions


# Print out tensors and their shapes
